
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend-depl
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 8089
    targetPort: 8089
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: AAA
        ports:
        - containerPort: 8089
        env:

        - name: SPRING_DATASOURCE_URL
          
          value: "jdbc:mysql://mysql-service:3306/achatdb?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
          

        - name: SPRING_DATASOURCE_USERNAME
          
          value: "root"
          

        - name: SPRING_DATASOURCE_PASSWORD
          
          value: "root"
          

