
apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: backend-depl
spec:
  type: NodePort
  selector:
    app: backend
  ports:
  - port: 3000
    targetPort: 3000
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: backend-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: yosri69/backend-nodejs
        ports:
        - containerPort: 3000
        env:

        - name: password
          
          value: "root"
          

