
apiVersion: v1
kind: Service
metadata:
  name: springboot-backend-service
  namespace: achat-depl
spec:
  type: NodePort
  selector:
    app: springboot-backend
  ports:
  - port: 8089
    targetPort: 8089
---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: springboot-backend
  namespace: achat-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: springboot-backend
  template:
    metadata:
      labels:
        app: springboot-backend
    spec:
      containers:
      - name: springboot-backend
        image: ikbel436/achat_backend
        ports:
        - containerPort: 8089
        env:

        - name: SPRING_DATASOURCE_URL
          
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: SPRING_DATASOURCE_URL
          

        - name: SPRING_DATASOURCE_USERNAME
          
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: SPRING_DATASOURCE_USERNAME
          

        - name: SPRING_DATASOURCE_PASSWORD
          
          valueFrom:
            configMapKeyRef:
              name: backend-config
              key: SPRING_DATASOURCE_PASSWORD
          

        - name: CUSTOM_ENV_VAR
          
          value: "custom_value"
          

