apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: C:\Users\LENOVO\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
    kompose.version: 1.31.2 (a92241f79)
  creationTimestamp: null
  labels:
    io.kompose.service: nodejs-kubernetes
  name: nodejs-kubernetes
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: nodejs-kubernetes
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: C:\Users\LENOVO\AppData\Local\Microsoft\WinGet\Packages\Kubernetes.kompose_Microsoft.Winget.Source_8wekyb3d8bbwe\kompose.exe convert
        kompose.version: 1.31.2 (a92241f79)
      creationTimestamp: null
      labels:
        io.kompose.network/backend-idp-default: "true"
        io.kompose.service: nodejs-kubernetes
    spec:
      containers:
        - env:
            - name: MONGO_DB_URL
              value: mongodb+srv://yosri:XympO44V7qQoumfS@idp.i24g5rc.mongodb.net/
            - name: PORT
              value: "80"
          image: local-nodejs-kubernetes
          name: nodejs-kubernetes
          imagePullPolicy: Never
          ports:
            - containerPort: 80
              hostPort: 8099
              protocol: TCP
          resources: {}
      restartPolicy: Always
status: {}
